[profile.default]
src = "src"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
bsc = "${RPC_BSC_MAINNET}"
bsc-testnet = "${RPC_BSC_TESTNET}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
bsc-testnet = { key = "${BSC_ETHERSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
